[options]
library = "AccountsService"
version = "1.0"
min_cfg_version = "23.13.0"
target_path = "."
girs_directories = ["../accountsservice-gir-files"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true
use_gi_docgen = false
generate_builder = true

generate = [
  "AccountsService.User",
  "AccountsService.UserAccountType",
  "AccountsService.UserPasswordMode",
  "AccountsService.UserManager",
  "AccountsService.UserManagerError",
]

manual = [
  "GLib.Variant",
  "GLib.Error",
  "Gio.AsyncResult",
  "Gio.AsyncReadyCallback",
  "Gio.Cancellable",
]
