[options]
library = "AccountsService"
version = "1.0"
min_cfg_version = "23.13.0"
target_path = "."
girs_directories = ["../../accountsservice-gir-files"]
work_mode = "sys"
single_version_file = true

external_libraries = ["GLib", "Gio", "GObject"]
